#!/bin/bash

SCALA_VERSION=2.11.12 ALMOND_VERSION=0.1.9

## Get sbt like an idiot
curl -L -o sbt-0.13.11.tgz https://piccolo.link/sbt-0.13.11.tgz
tar -xvzf sbt-0.13.11.tgz

# Try to publish visualizer
git clone https://github.com/azidar/visualizer.git
cd visualizer
../sbt/bin/sbt publishLocal

# Install coursier
curl -L -o coursier https://git.io/coursier
chmod +x coursier

# Install almond
./coursier bootstrap \
    -r jitpack \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    --sources --default=true \
    -o almond
./almond --install

# Install required Jupyter/JupyterLab extensions
jupyter labextension install @jupyterlab/plotly-extension

# Install custom Javascript for solutions
mkdir -p ~/.jupyter/custom
cp source/custom.js ~/.jupyter/custom/custom.js
